### ISSUE TITLE
Vertical Alignment of Divs

### ISSUE THREAD

**Issue by valkyrienyanko** [valkyrienyanko/ValksMatchMaker#10]
Right now I'm guessing on how to center divs vertically, it would be nice if there was a better way.
```css
.info {
	margin: auto;
	width: 50%;
	transform: translateY(150%);
}

.chat {
	display: none;
}

.status {
	margin: auto;
	transform: translateY(900%);
	display: none;
}
```
